'Brand: 765AS':
  - RDFs/765AS.rdf
  - RDFs/Units/765AS.rdf
  - RDFs/Clothes/IdolM@ster.rdf
  - RDFs/Clothes/IdolM@sterSP.rdf
  - RDFs/Clothes/IdolM@ster2.rdf
  - RDFs/Clothes/OneForAll.rdf
  - RDFs/Clothes/PlatinumStars.rdf
  - RDFs/Clothes/StetllaStage.rdf
  - RDFs/Clothes/StarLitSeason.rdf

'Brand: シンデレラガールズ':
  - RDFs/CinderellaGirls.rdf
  - RDFs/Units/CinderellaGirls.rdf
  - RDFs/Clothes/CinderellaGirls.rdf
  - RDFs/Clothes/CinderellStageCommon.rdf
  - RDFs/Clothes/CinderellStagePersonal.rdf
  - RDFs/Clothes/CinderellStageUnit.rdf
  - RDFs/CinderellaGirlsRanking/**/*.rdf

'Brand: ミリオンライブ':
  - RDFs/765MillionStars.rdf
  - RDFs/Units/MillionLive.rdf
  - RDFs/Clothes/MillionLive.rdf
  - RDFs/Clothes/TheaterDaysCommon.rdf
  - RDFs/Clothes/TheaterDaysPersonal.rdf
  - RDFs/Clothes/TheaterDaysUnit.rdf

'Brand: SideM':
  - RDFs/SideM.rdf
  - RDFs/Units/SideM.rdf
  - RDFs/Clothes/SideM.rdf
  - RDFs/Clothes/LiveOnStageCommon.rdf
  - RDFs/Clothes/LiveOnStagePersonal.rdf
  - RDFs/Clothes/LiveOnStageUnit.rdf

'Brand: シャイニーカラーズ':
  - RDFs/283.rdf
  - RDFs/Units/ShinyColors.rdf
  - RDFs/Clothes/ShinyColorsCommon.rdf
  - RDFs/Clothes/ShinyColorsPersonal.rdf
  - RDFs/Clothes/ShinyColorsUnit.rdf
