version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: run rdflint
        command: |
          RDFLINT_VERSION=0.0.3
          wget https://jitpack.io/com/github/imas/rdflint/$RDFLINT_VERSION/rdflint-$RDFLINT_VERSION-all.jar
          java -jar rdflint-$RDFLINT_VERSION-all.jar -config .circleci/rdflint-config.yml
  unit_memberOf:
    build:
      docker:
      - image: circleci/node:latest
      working_directory: ~/unit
      steps:
      - ckeckout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
        name: make unit_memberOf
        command: |
          ls
          wget https://raw.githubusercontent.com/crssnky/imasparql_tools/master/Unit_memberOf/app.js
          wget https://raw.githubusercontent.com/crssnky/imasparql_tools/master/Unit_memberOf/package.json
          rm -f ./RDFs/Unit_memberOf.rdf
          npm install
          node app.js > ./RDFs/Unit_memberOf.rdf
          git config user.email "50269637+Chihya-bot@users.noreply.github.com"
          git config user.name "Chihya-bot"
          git add ./RDFs/Unit_memberOf.rdf
          git commit -m "[ci skip] Update Unit_memberOf"
          git push --set-upstream origin add_Unit
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflow:
  version: 2
  deploy:
    jobs:
      - build
      - unit_memberOf
        filters:
          branches:
            only:
              - Add_Unit
